### ISSUE TITLE
[Feature] Blacklist feature.

### ISSUE THREAD

**Issue by murao-kun** [SuperMartijn642/DurabilityTooltip#8]
**Is your feature request related to a problem? Please describe.**
This what could happen sometime with someitems. (There is more)
![image](https://user-images.githubusercontent.com/110398598/187876518-b65dbe42-7d88-4094-85d2-ae883f0994fb.png)

**Describe the solution you'd like**
Blacklist feature will make it fixed. Good tool for modpack makers.

**Comment by SuperMartijn642** [comment]
I added a config option the blacklist items from specific mods. Blacklisting individual items is a bit more difficult since I can't use tags as Durability Tooltip is a client-side only mod, thus for now that is not available.

I also added Supplementaries and Tinkers' Construct as default values in the blacklist.

The option to blacklist certain mods is available now in Durability Tooltip version 1.1.5.
Thank you for the suggestion!

**Comment by murao-kun** [comment]
Thank you for implementing!
